---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: 了解NetApp Console的功能和資料服務的最新變化。 
---
= NetApp Console中的最新更改
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解NetApp Console的功能和資料服務的最新變化。要查看完整的發布歷史記錄，請訪問link:release-notes-index.html["全套發行說明"]針對每項單獨的服務。

[NOTE]
====
以下服務已棄用：

邊緣緩存:: 邊緣快取服務於 2024 年 8 月 7 日刪除。
Kubernetes:: 2024 年 8 月 7 日，對發現和管理 Kubernetes 叢集的支援被取消。
遷移報告:: 遷移報告服務已於 2024 年 8 月 7 日移除。
營運彈性:: 營運彈性功能已於 2025 年 8 月 22 日移除。
補救措施:: 補救服務已於 2024 年 4 月 22 日刪除。


====


[[15-july-2026]]
== 2026年7月15日



[[console-setup-and-administration]]
=== 控制台設定和管理



==== Console 代理 4.9.0

4.9.0 版本同時支援標準模式和受限模式。

此版本的 Console 代理程式包含安全性改善和錯誤修正。



==== NetApp Console管理

.支援 Cloud Volumes ONTAP 的角色型存取控制
Console 支援 Cloud Volumes ONTAP 的角色型存取控制。

link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["深入瞭解 Cloud Volumes ONTAP 的角色型存取"^]。



[[amazon-fsx-for-ontap]]
=== Amazon FSX for ONTAP



==== 從 NetApp Console 的工作負載中移除 GenAI 工作負載

GenAI 工作負載已從 NetApp Console 的工作負載中移除。



[[14-july-2026]]
== 2026年7月14日



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP 9.19.1 RC

現在您可以使用 NetApp Console 在 Google Cloud 中部署和管理 Cloud Volumes ONTAP 9.19.1 的候選發行版本 （RC）。此版本尚不支援在 Amazon Web Services （AWS） 和 Microsoft Azure （Azure） 中部署和升級。

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["深入瞭解此版本的 Cloud Volumes ONTAP"^]。



==== Cloud Volumes ONTAP HA 支援下一代 Google Cloud VM

在 9.19.1 版本中，NetApp 將 Cloud Volumes ONTAP 高可用性 （HA） 部署從 N2 VM 移轉至下一代 Google Cloud C3 系列 VM，以提供更快速且更具擴充性的體驗。


NOTE: 此支援僅適用於單可用區 (AZ) HA 部署。

現在，您可以在 Google Cloud 中部署 Cloud Volumes ONTAP 9.19.1 及更高版本時，充分利用 C3 系列虛擬機器。這些虛擬機器效能更佳，容量上限更高。它們採用 Google Virtual NIC （gVNIC） 和 Hyperdisk Balanced 磁碟，可在密集型工作負載下提供動態效能。

如果您的 Cloud Volumes ONTAP 系統執行的是 9.19.1 或更新版本，則用於在單一 AZ 中輕鬆部署的預先設定套件會自動使用 C3 VM，同時可讓您根據工作負載需求自訂 IOPS 和處理量參數。同樣地，在建立集合體時，您可以新增 Zonal Hyperdisk Balanced 磁碟，以在 Google Cloud 中實現更佳的效能和擴充性。您也可以選擇 C3 系列機器的 LSSD 變體，以獲得預設的 Flash Cache 支援。

請注意以下幾點：

* 在 Cloud Volumes ONTAP 部署中，您無法將 C3 VM 變更為 N2 系列 VM，反之亦然。但是，您可以在 C3 系列的不同變體之間切換執行個體類型。
+

NOTE: 根據所連接的資料磁碟數量，在 C3 系列實例中變更實例類型可能需要更長時間。請事先規劃配置，以避免影響效能。

* 變更執行個體類型時，如果您選擇 c3-standard-44 或 c3-standard-88 及其本機 SSD （LSSD） 變體作為目標 VM，則會自動套用 Google 網路服務輸出網路層 _Tier-1_。如果您切換回任何其他 C3 變體，則輸出網路層將設定為 _Standard_。
+

NOTE: 將出口網路層級變更為 _Tier-1_ 會產生額外費用。請據此規劃部署和升級。

* 如果選擇 C3 的 LSSD 變體，則預設會啟用 Flash Cache。即使目標變體支援 Flash Cache，您也無法在 Cloud Volumes ONTAP 部署中切換 C3 LSSD 變體。
* 在 C3 VM 上，您可以為新的聚合和現有的聚合新增磁碟區。
* 將 N2 VM 類型的 Cloud Volumes ONTAP 系統複製到 C3 VM 類型時，磁碟類型預設為 Hyperdisk Balanced。
* 您可以透過 NetApp Console 或使用 `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API 在新增聚合時變更 IOPS 和吞吐量設定。


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud 中 Cloud Volumes ONTAP 支援的組態"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google 文件：C3 機器系列"^]



==== 簡化 Google Cloud 中的 Cloud Volumes ONTAP 部署

現在，您可以使用 *Quick create* 精靈在 Google Cloud 中部署 Cloud Volumes ONTAP，支援單一節點和高可用性 (HA) 配置。此簡化流程減少了步驟，在單一頁面上自動設定預設值，並將導覽步驟降至最少，從而實現更快、更輕鬆的部署。

.相關連結
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["使用 Quick create 在 Google Cloud 中部署 Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["使用 Google Cloud 中的進階選項部署 Cloud Volumes ONTAP"^]




==== 為 Cloud Volumes ONTAP 引入存取角色

NetApp 為 Cloud Volumes ONTAP 引入身分與存取管理 （IAM） 角色，從而實現基於角色的存取控制 （RBAC），以提高安全性並簡化合規性。使用者仍可使用現有憑證登入 NetApp Console 執行 Cloud Volumes ONTAP 操作。但是，驗證現在透過身分聯合進行路由，使 Console 管理員能夠對這些功能進行更精細的控制。每個使用者必須擁有以下角色之一，才能對 Cloud Volumes ONTAP 執行任何操作。若無角色，使用者將無法檢視或存取 Cloud Volumes ONTAP 執行個體。

* *Cloud Volumes ONTAP viewer*：授予對 Cloud Volumes ONTAP 畫面和索引標籤的唯讀存取權限。在此角色中，某些畫面和操作按鈕將被停用。
* *Cloud Volumes ONTAP operator*：支援日常管理任務，例如新增磁碟區、管理儲存和設定複製。
* *Cloud Volumes ONTAP admin*：提供對所有 Cloud Volumes ONTAP 操作的完全存取。


Console 管理員可透過「管理 > 身分」為 Cloud Volumes ONTAP 使用者指派角色。角色權限是基於使用者所在的組織，並套用於該組織中的所有 Cloud Volumes ONTAP 系統。

Cloud Volumes ONTAP 使用本機快取來強制執行角色型存取控制 （RBAC），該快取記錄每個使用者的權限，並每小時自動重新整理一次。當使用者被指派新角色或現有角色發生變更時，變更可能需要長達一個小時才能生效，生效後，所有角色允許的工作流程都將啟用。


NOTE: 首次部署 Console 代理程式或將現有 Console 代理程式升級至 Console 4.9.0 或更高版本時，系統會執行一次性初始化過程，自動為組織中的所有現有使用者指派 Cloud Volumes ONTAP 角色。此過程可能需要長達 30 分鐘才能完成。完成後，Console 會將對應的角色指派給現有使用者。

Cloud Volumes ONTAP 角色適用於 Amazon Web Service (AWS)、Microsoft Azure (Azure) 和 Google Cloud 環境。

.相關連結
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console 存取角色"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["NetApp Console 中的 Cloud Volumes ONTAP 存取角色"^]




[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== 備份和復原



==== 增強對所有工作負載的多儲存貯體支援

在此備份與還原版本中，您現在可以跨不同的雲端供應商，為每個系統保護多達 100 個儲存桶的工作負載。

有關 NetApp Backup and Recovery 的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["了解 NetApp Backup and Recovery"]。



[[disaster-recovery]]
=== 災難復原



==== Kubernetes 更新

災難恢復針對基於 Kubernetes 的工作負載引入了以下變更：



===== 從「網站」選單管理 Trident Protect

現在，災難復原功能支援直接從災難復原使用者介面中的「網站」選單管理 Trident Protect。您可以升級 Trident Protect 或將其從災難復原功能中移除，從而簡化 Kubernetes 資源的管理。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["管理網站"^]。



==== VMware 更新

災難復原功能針對基於 VMware 的工作負載引入了以下變更：



===== 空資料存放區容錯移轉

現在，即使複製計劃中包含空資料存放區，也可以成功進行容錯移轉，而無需將其從計劃中排除或強制執行容錯移轉。在容錯移轉期間，Disaster Recovery 會自動將空資料存放區掛載到災難復原站台，從而允許新增 VM 並對其進行保護，以進行容錯回復作業。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["容錯移轉至遠端站台"^]。



===== vCenter 網路自動映射

現在您可以在 vCenter 層級（即複製計畫對話方塊之外）設定網路對映關係。設定完成後，災難復原會在您新增或編輯複製計畫時自動套用這些網路對映，從而簡化複製計畫管理。

災難復原功能繼續支援按計劃進行覆蓋。複製計劃中定義的現有網路映射仍然可以按網路進行編輯；這些映射優先於 vCenter 層級定義。



==== 災難復原檢視器角色限縮

「升級系統」標籤已從災難復原檢視者角色中移除。此變更旨在使該角色與唯讀使用者的體驗更加一致。link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["了解 NetApp Disaster Recovery 中的使用者角色和權限"^]。



==== 系統效能提升

災難復原功能引進了多項變更，旨在降低系統資源消耗並提升各項作業的效能。



[[07-july-2026]]
== 2026年7月7日



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== 從使用者行為警報中排除檔案路徑

Ransomware Resilience 支援將特定檔案路徑從使用者行為監控警示中排除。如果您確定這些檔案路徑不存在風險，或者您正在對可能觸發警示的磁碟區中的檔案進行操作，則可以將其排除在外。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["從警報中排除檔案路徑"^]。



==== 適用於 Microsoft Sentinel 的 ARM 模板

Ransomware Resilience 現在提供 Azure Resource Manager （ARM） 範本，用於將 Microsoft Sentinel 連接至 SIEM，提供一種輔助部署的方法。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["連接到安全資訊和事件管理 (SIEM) 系統以進行威脅偵測和分析"^]。



[[29-june-2026]]
== 2026 年 6 月 29 日



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== 對使用者活動警報的自動回應

Ransomware Resilience 現已支援在產生使用者活動警報時自動建立快照和封鎖使用者。透過自動回應，您可以在產生警告後立即封鎖使用者並建立快照以進行復原，從而實現更快速的回應，無需人工介入。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["自動回應使用者活動警示"^]。



[[digital-advisor]]
=== 數位顧問



==== 健康檢查 GraphQL 遷移和資料準確性改進

健康檢查模組已增強，資料準確性更高，版本建議也與現行標準保持一致。作為此版本更新的一部分，該模組已從公共 API 遷移至 GraphQL，從而提升了效能，提供更靈活的查詢方式及長期支援。



===== 推薦軟體

健康檢查模組中推薦的軟體增強功能現在可以提供更準確、更一致的資料。

* 機櫃和磁碟機數量在韌體版本顯示下會顯示每個系統的準確值，不再包含 HA 配對數量。
* 現在，最低版本和最新版本建議是根據叢集的有效版本在叢集層級計算的，符合現行標準——以前，這些建議是在節點層級計算的。




===== AutoSupport 資料依賴性

由於後端改進，AutoSupport 採用率和建議軟體視圖均依賴最新的 AutoSupport 資料。這可能會以下列方式影響您目前的視圖：

[cols="30,70"]
|===
| 情境 | 受影響的系統 


| 未顯示資料 | 自 2025 年 10 月以來未傳送 AutoSupport 的系統 


| 過時的值 | 過去 30 天內未傳送 AutoSupport 的系統 
|===
在上述受影響的系統上重新觸發 AutoSupport，以還原健康檢查視圖中的最新資料。



[[keystone]]
=== Keystone

NetApp Console中Keystone儀表板的新增強功能：



==== 查看 MetroCluster 訂閱的 ADP 授權分發狀況

「進階資料保護 (ADP)」標籤中新增了「授權分發」子選項卡，讓您可以查看 MetroCluster 合作夥伴叢集的 ADP 授權使用情況。若要深入瞭解，請參閱  https://docs.netapp.com/us-en/keystone-staas/integrations/adp-tab.html["查看您的 Keystone MetroCluster 訂閱的使用與健康狀況"]。



==== 檢視磁碟區的勒索軟體防護狀態

「資產」中的「叢集中的磁碟區」標籤現在包含一個「ARP 狀態」欄，該欄顯示每個磁碟區是否啟用或停用自主勒索軟體防護 (ARP)，讓您了解受管資產的勒索軟體防護狀況。若要深入瞭解 ARP，請參閱 https://docs.netapp.com/us-en/ontap/anti-ransomware/["ONTAP 中的自主勒索軟體防護 (ARP)"^]。



==== 使用「回饋」標籤分享回饋

現在，您可以使用 Keystone 控制面板中位於螢幕右下角的全新「回饋」索引標籤，從任何螢幕提供回饋。點擊該索引標籤將開啟一個面板，您可以在其中分享您的體驗並直接向 NetApp 提交意見。



==== 改善容量使用情況和訂閱到期提醒

系統產生的監控器現在可針對容量使用情況和訂閱到期情況提供更精細的警示。

訂閱到期提醒現在會在到期前五個門檻觸發：到期前 180 天、90 天、60 天、30 天和 7 天，嚴重程度會隨著到期日的臨近而從通知等級升級到緊急等級。

對於容量使用情況，突發警報閾值現在基於您訂閱的承諾突發百分比，而不是固定的 20%。例如，如果您的承諾突發百分比為 40%，則當承諾容量利用率達到 140% 時，將觸發嚴重警報。

若要深入瞭解，請參閱  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["查看並建立 Keystone 訂閱的警報監控器"]。



[[15-june-2026]]
== 2026 年 6 月 15 日



[[console-setup-and-administration]]
=== 控制台設定和管理



==== 私有模式發布（4.7.0）

現在可以從 https://mysupport.netapp.com/site/downloads["NetApp 支援網站"^]下載新的私人模式版本

4.7.0 版本包含以下 NetApp Console 元件和服務的更新。

[cols="3*"]
|===
| 組件或服務 | 此版本中包含的版本 | 自上次私有模式版本發布以來的變更 


| Console 代理程式 | 4.7.0 | 前往 https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["NetApp Console 頁面新增功能"^]並參考版本 4.7.0 中包含的變更。 


| NetApp Backup and Recovery | 5.4.0（2026年6月8日） | 前往  https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["NetApp Backup and Recovery 頁面的最新消息"^]。 


| NetApp Data Classification | 1.54.0（2026年5月11日） | 前往  https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["NetApp Classification 頁面新增功能"^]。 
|===


[[backup-and-recovery]]
=== 備份和復原



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.06*：此版本包含 Trident Protect 26.06。
* *恢復期間跳過應用程式建立*：現在您可以在復原作業期間跳過自動建立應用程式自訂資源物件。這樣可以減少應用程式清單中不必要的條目。
* *還原 VM 持久性磁碟區請求*：還原 VM 型應用程式時，現在可以還原個別持久性磁碟區請求，而無需還原整個虛擬機器，當特定磁碟或磁碟區受到損毀或資料遺失影響時，可加快復原速度。
* *作業監控改進*：作業監控功能現已增強，可更清楚顯示 Kubernetes 保護作業的狀態。您可以查看作業和子作業的詳細狀態資訊，以及每個作業使用的目標儲存。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



[[11-june-2026]]
== 2026 年 6 月 11 日



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAP 支援新的 Azure 區域

現在您可以在馬來西亞西部（malaysiawest）區域的 Azure 中，在單一和多個可用區部署 Cloud Volumes ONTAP 9.12.1 GA 及更高版本。這包括對單節點和高可用性（HA）部署的支援。

有關所有地區的清單，請參閱  https://bluexp.netapp.com/cloud-volumes-global-regions["Azure 下的全球區域地圖"^]。



[[08-june-2026]]
== 2026 年 6 月 08 日



[[console-setup-and-administration]]
=== 控制台設定和管理



==== Console 代理 4.8.0

4.8.0 版本同時支援標準模式和受限模式。

此版本的 Console 代理程式包含安全性改善和錯誤修正。



==== NetApp Console管理

本次版本更新包含了安全性改善和漏洞修復。



[[backup-and-recovery]]
=== 備份和復原



==== ONTAP Volumes 工作負載增強功能

在此版本中，ONTAP Volumes 工作負載引入了以下增強功能：

*支援 S3 相容的雲端儲存*：NetApp Backup and Recovery for Volumes 工作負載現在支援備份到 S3 相容的雲端儲存。

有關保護 ONTAP Volumes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保護 ONTAP Volumes 工作負載總覽"]。



==== Hyper-V 工作負載增強功能

在此版本中、Hyper-V 工作負載引入了以下增強功能：

* *將檔案和資料夾還原到客體 VM 的功能改進*：現在您可以將主要或次要儲存設備上快照中的檔案和資料夾還原到客體 Windows VM。CIFS 和 SAN VM 現在支援此功能。
* *保護群組現在使用主機時區排程*：保護群組現在使用 Hyper-V 主機的時區。在引入主機時區排程功能之前建立的保護群組將繼續使用其先前設定的時間（通常為 UTC）。若要將這些保護群組更新為使用 Hyper-V 主機時區，您必須重新建立排程。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["建立和管理 Hyper-V 工作負載的保護群組"]。


有關保護 Hyper-V 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["保護 Hyper-V 工作負載概述"]。



==== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進下列增強功能：

* *保護群組現在使用主機時區排程*：保護群組現在使用宿主 VMware vCenter 伺服器的時區。在引入主機時區排程功能之前建立的保護群組將繼續使用先前設定的時區（通常為 UTC）運作。若要使用 vCenter 時區，您必須重新建立排程。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["建立並管理 VMware 工作負載的保護群組"]。


有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。



[[data-classification]]
=== 資料分類



==== 一般改善

此版本的 Data Classification 包含安全性改進和效能增強。



[[disaster-recovery]]
=== 災難復原



==== Kubernetes 更新

災難恢復針對基於 Kubernetes 的工作負載引入了以下變更：



===== 測試 Kubernetes 工作負載的容錯移轉支援

災難復原功能現已支援對 Kubernetes 工作負載的故障轉移流程進行測試。透過測試故障轉移，您可以驗證災難復原計劃。測試完成後，您可以清理測試故障轉移，系統會自動清理測試資源，從而降低系統開銷並確保環境的一致性。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["測試容錯移轉程序"^]。



===== 排程測試容錯移轉

現在，您可以透過排程測試容錯移轉來自動化災難恢復測試。您可以設定定期測試容錯移轉的排程，以持續驗證恢復計畫而無需人工介入，有助於維持對恢復目標的信心並符合法規遵循要求。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["管理複寫計畫"^]。



===== Kubernetes 工作負載的排程探索

透過排程探索，您可以控制 Disaster Recovery 掃描新 Kubernetes 工作負載的頻率。您可以設定探索時間間隔，以符合您的作業節奏，減少不必要的系統負荷，同時確保及時偵測並保護新的工作負載。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["自訂探索排程"^]。



==== VMware 更新



===== 保護空資料存放區

災難復原功能現在允許為不包含任何虛擬機器（VM）的資料儲存配置保護。之後新增到資料儲存中的任何 VM 都會被 Disaster Recovery 自動偵測，此時您需要提供link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["對應資訊"^]。

將空資料存放區新增至保護計畫時，您必須先從保護計畫中移除該資料存放區，然後再執行容錯移轉，或執行強制容錯移轉。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["容錯移轉至遠端站台"^]。



===== 將先前排除的資料存放區還原至保護計畫

先前被排除在保護範圍之外的資料存放區現在可以重新納入保護範圍。這項增強功能在長期管理和更新災難恢復組態時提供了更大的靈活性。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["管理站台、資源群組和複寫計畫"^]。



===== 加快基於 VMFS 的資料存放區容錯移轉速度

災難復原功能提升了基於 VMFS 的資料存放區的容錯移轉效能。主機匯流排介面卡 (HBA) 重新掃描和資料存放區掛載作業現在可以並行執行，從而縮短整體容錯移轉時間，並最大限度地減少還原事件期間的停機時間。

如需容錯移轉的詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["透過災難復原進行容錯移轉"^]。



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== 增強保護策略的靈活性

Ransomware Resilience 現在提供了更靈活的勒索軟體偵測策略選擇。以前，所有勒索軟體防護策略都必須包含加密偵測。現在，您可以啟用僅包含使用者行為偵測的勒索軟體防護策略。

保護策略仍然可以同時包含加密偵測和可疑使用者行為偵測。任何保護策略還可以新增封鎖檔案副檔名的功能。

如果停用現有原則的部分保護策略，則在先前原則版本下建立的任何現有警示只能標記為「已解決」，而不能標記為「已忽略」。例如，如果您的保護策略包含加密偵測和可疑使用者行為偵測，但您停用了加密偵測，則只能解決該工作負載的現有加密警示。

如需詳細資訊，請參閱link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["使用 NetApp Ransomware Resilience 保護策略來保護工作負載"^]。



==== SOAR 劇本增強功能

勒索軟體恢復能力 SOAR 劇本現在提供了在阻止使用者或將磁碟區離線後的補救步驟。如果該操作被判定為並非勒索軟體威脅，您現在可以將磁碟區重新上線並解除對使用者的封鎖。

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["整合 SOAR 劇本"^]。



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== AWS 中 Cloud Volumes ONTAP 的新 EC2 執行個體支援

Cloud Volumes ONTAP 9.16.1 及更高版本支援 M6id 和 M6idn EC2 執行個體系列，適用於 AWS 中新建和現有的單節點及高可用性（HA）配對部署。與第五代通用系統相比，這些第六代執行個體提供更快的處理能力、更強大的網路功能和更高的效能。

* *M6id 實例*：兼具運算和記憶體容量，並配備高速、低延遲的本地 NVMe 儲存。所有 M6id 執行個體大小均支援 Flash Cache。這些實例非常適合資料記錄和媒體處理等工作負載。
* *M6idn 執行個體*：提供與 M6id 執行個體相同的本機 NVMe 儲存功能。所有 M6idn 執行個體大小均支援 Flash Cache。


我們不建議將較小尺寸的 m6id.xlarge、m6id.2xlarge、m6idn.xlarge 和 m6idn.2xlarge 執行個體類型用於高效能或記憶體密集型工作負載。對於這些工作負載，請使用具有更高核心數和更大記憶體的執行個體類型。

如需詳細資訊，請參閱 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["AWS 中 Cloud Volumes ONTAP 支援的組態"^]。



[[03-june-2026]]
== 2026 年 6 月 03 日



[[lifecycle-planning]]
=== 生命週期規劃



==== 生命週期規劃功能名稱更新

以下生命週期規劃功能已變更名稱：

* 技術更新功能現在稱為 *System Refresh*。了解如何操作 https://docs.netapp.com/us-en/console-lifecycle-planning/use/tech-refresh.html["評估系統重新整理"]。
* 容量擴充功能現在稱為 *Storage Expansion*。了解如何操作 https://docs.netapp.com/us-en/console-lifecycle-planning/use/capacity-add.html["擴充儲存空間"]。
* 續訂功能現已更名為「支援續訂」。了解如何操作 https://docs.netapp.com/us-en/console-lifecycle-planning/support/task-support-registration.html["註冊以獲得支援"]。




[[digital-advisor]]
=== 數位顧問



==== Digital Advisor 小工具名稱更新

以下 Digital Advisor 功能已更改名稱：

* Tech Refresh 功能現已更名為 System Refresh。了解如何link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["評估系統重新整理"]。
* 容量新增功能現已更名為儲存擴充。了解更多link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor 小工具"]。
* 續訂功能現已更名為 Support Renewals。了解更多link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Digital Advisor 小工具"]。




[[26-may-2026]]
== 2026 年 5 月 26 日



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== Google Cloud NetApp Volumes 支援（預覽版）

勒索軟體韌性現在支援在 Google Cloud NetApp Volumes 系統中建立保護群組，使您能夠將多個工作負載組織在一個政策下，以簡化管理。

如需更多資訊，請參閱link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["在 Ransomware Resilience 中建立保護群組"^]。



[[25-may-2026]]
== 2026 年 5 月 25 日



[[keystone]]
=== Keystone

NetApp Console中Keystone儀表板的新增強功能：



==== 改進了訂閱時間軸中同一天多次更新的顯示方式

訂閱時間軸圖表現在會在同一天發生多個不同類型的訂閱更新時顯示一個數字，而不是顯示單獨的圖示。將滑鼠懸停在該數字上即可查看當天所有更新類型。下載的報告包含每個更新的單獨行，為您提供所有變更的完整記錄。若要深入瞭解，請參閱  https://docs.netapp.com/us-en/keystone-staas/integrations/subscription-timeline.html["查看您的 Keystone 訂閱時間軸"]。



[[18-may-2026]]
== 2026 年 5 月 18 日



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== Google Cloud NetApp Volumes 支援（預覽版）

勒索軟體復原功能現已支援 Google Cloud NetApp Volumes 系統，讓您能夠有效率地偵測並應對 Google Cloud NetApp Volumes 中的勒索軟體威脅。在進行發現時,勒索軟體復原功能會自動顯示來自 Google Cloud NetApp Volumes 系統的工作負載。發現這些系統後,它們會顯示在勒索軟體復原功能控制面板中。目前,勒索軟體復原功能對 Google Cloud NetApp Volumes 的支援仍處於預覽階段。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["了解勒索軟體復原能力"^]。如需 Google Cloud NetApp Volumes 支援範圍的相關資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["勒索軟體復原能力的限制"^]。



==== 乾淨還原增強功能

現在，乾淨恢復功能支援產生報告。透過報告，您可以檢視和評估乾淨復原操作，並將這些資訊儲存為 CSV 檔案以便離線使用。

現在，乾淨還原也支援停止分析。如果停止分析，則必須重新開始乾淨還原。

若要深入瞭解報告,請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["在 Ransomware Resilience 中下載報告"^]。若要深入瞭解還原,請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["使用乾淨還原來恢復工作負載"^]。



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== 簡化 Azure 中的 Cloud Volumes ONTAP 部署

現在，您可以使用快速建立功能在 Azure 中部署 Cloud Volumes ONTAP，支援單一節點和高可用性 (HA) 設定。與進階方法相比，此簡化流程減少了步驟，在單一頁面上自動設定預設值，並最大限度地減少了導覽，從而使部署更快、更輕鬆。

.相關連結
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["使用快速建立在 Azure 中部署 Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["使用 Azure 中的進階選項部署 Cloud Volumes ONTAP"^]




[[digital-advisor]]
=== 數位顧問



==== 健康狀況檢閱

自 2026 年 7 月起，Digital Advisor 中的 Wellness Review 功能將不再提供。如有任何疑問，請發送電子郵件至 mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#]。



[[12-may-2026]]
== 2026 年 5 月 12 日



[[cloud-volumes-ontap]]
=== Cloud Volumes ONTAP



==== AWS 中 Cloud Volumes ONTAP 和資料服務的彈性計費

NetApp 在 AWS 中為您的 Cloud Volumes ONTAP 訂閱提供了更進階的計費選項，讓您能更靈活地控制 Cloud Volumes ONTAP 容量與 NetApp 資料服務（例如 NetApp Backup and Recovery）的付款方式。過去，所有 Cloud Volumes ONTAP 及資料服務的使用情形，都是透過 AWS marketplace 中的 NetApp Intelligent Services（NIS）條目一起計費。

由於 AWS 企業折扣方案（EDP）的變更，NetApp 在 AWS Marketplace 中推出了獨立的 Cloud Volumes ONTAP 訂閱，讓您可以將 Cloud Volumes ONTAP 容量的計費與資料服務的計費分開。這種分離方式讓您更靈活地管理 EDP 抵扣額度和成本。NetApp 建議您使用獨立訂閱來更好地管理 Cloud Volumes ONTAP 的使用成本，同時在 2026 年 7 月 31 日 EDP 要求生效後，繼續使用 NIS 訂閱來支付資料服務的計費。

AWS 中的獨立 Cloud Volumes ONTAP 訂閱僅支援有效的基於容量的 Essentials 或 Freemium 許可套餐。Professional 套餐不支援。您可以選擇最適合您需求的計費方式：

* *獨立 Cloud Volumes ONTAP 訂閱（建議）*：您可以透過 AWS Marketplace 中的獨立訂閱支付 Cloud Volumes ONTAP 的使用費用，同時繼續透過 NIS 訂閱支付資料服務費用。對於大多數在 NetApp Console 中同時擁有獨立訂閱和 NIS 訂閱並與其 AWS 帳戶相關聯的客戶，這是建議的選擇。
* *合併 NIS 訂閱*：透過現有的 NIS 清單同時支付 Cloud Volumes ONTAP 和資料服務的費用。此合併方案適用於在 NetApp Console 中僅關聯了 NIS 訂閱的現有客戶。但是，NetApp 建議您設定 Cloud Volumes ONTAP 使用量的計費偏好設定，並切換到獨立訂閱，以便更好地管理成本。


根據您的訂閱類型，您將遇到以下情況：

.僅限獨立訂閱（新客戶）
如果您在 NetApp Console 中僅擁有與您的 AWS 帳戶關聯的獨立 AWS 訂閱，而沒有 NIS 訂閱，則在部署期間只能選擇 Essentials 授權包。資料服務的 *Backup and Recovery* 選項對您不可用。

.獨立訂閱和 NIS 訂閱（現有客戶）
如果您的 AWS 帳戶同時關聯了 NIS 和獨立訂閱，且您尚未透過 NetApp Console 中的 *Billing preferences* 標籤設定帳單首選項，則 Cloud Volumes ONTAP 的使用量預設仍透過 NIS 計費。對於執行 Professional 套餐的任何 Cloud Volumes ONTAP 執行個體，這也是預設設置，因為獨立清單不支援 Professional。您可以設定帳單首選項並選擇每項服務的計費方式：

* 將獨立訂閱設定為 Cloud Volumes ONTAP（包含 Essentials 套餐）的首選計費帳戶。如果您只有 Professional 套餐，可以將其轉換為 Essentials 套餐，並透過設定計費首選項來收取 Cloud Volumes ONTAP 的使用費用。我們推薦這種方法，因為它有助於您更有效地管理 Cloud Volumes ONTAP EDP 積分。
* 使用 NIS 訂閱進行資料服務計費，或透過 Professional 套餐計費 Cloud Volumes ONTAP 使用量。在部署期間，啟用 *Backup and Recovery* 資料服務，並選擇 Professional 授權套餐，以透過 NIS 訂閱計費資料服務。


.僅限 NIS 訂閱用戶（現有客戶）
如果您是已擁有與 AWS 帳戶關聯的 NIS 訂閱的現有客戶，則此說明適用。您可以繼續像現在一樣同時對 Cloud Volumes ONTAP 和資料服務進行計費。但是，NetApp 建議您切換到獨立訂閱模式，以便更好地管理 Cloud Volumes ONTAP 的使用成本：

* 在 AWS 入口網站上訂閱新的獨立清單。
* 將獨立訂閱連結至您的 AWS 帳戶。
* 將您的計費偏好設定為使用 Essentials 套餐的 Cloud Volumes ONTAP 獨立訂閱。
* （如適用）將您的 Professional 套件轉換為 Essentials 套件，並設定計費偏好設定。
* 繼續透過您的 NIS 訂閱進行資料服務計費。



NOTE: 使用多種訂閱類型或在清單之間遷移時，不會發生重複計量。

.相關連結
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["在 AWS 中設定 Cloud Volumes ONTAP 的授權"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["變更容量授權的收費方式"^]




[[11-may-2026]]
== 2026 年 5 月 11 日



[[console-setup-and-administration]]
=== 控制台設定和管理



==== Console 代理 4.7.0

4.7.0 版本同時支援標準模式和受限模式。

此版本的 Console 代理程式包含安全性改善和錯誤修正。



==== NetApp Console管理

本版本包含以下新功能。

.驗證您的 Console 組織
預設情況下，Digital Advisor 會顯示與貴公司關聯的所有 NetApp 帳戶，而不僅僅是您的 Console 組織。若要將 Digital Advisor 中顯示的內容限制為特定帳戶，請驗證您要與 Console 組織搭配使用的企業帳戶。link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["了解如何驗證您的 Console 組織"^]



[[backup-and-recovery]]
=== 備份和復原



==== Hyper-V 工作負載增強功能

在此版本中、Hyper-V 工作負載引入了以下增強功能：

* *保護 SAN 儲存設備上的 VM*：您現在可以保護 SAN 物件儲存設備上的 VM。
* *還原至備用位置增強功能*：現在可以從 SAN 儲存設備上的 VM 主要位置和次要位置還原至備用位置。
* *將檔案和資料夾還原至客體 VM*：您現在可以將主要儲存設備上快照中的檔案和資料夾還原至客體 Windows VM。此功能僅支援 CIFS VM。


有關保護 Hyper-V 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["保護 Hyper-V 工作負載概述"]。



==== KVM 工作負載增強功能

在此版本中、KVM 工作負載引入了以下增強功能：

*還原至替代位置*：您現在可以將 KVM VM 還原至替代目的地（此功能現已正式推出）。

有關保護 KVM 工作負載的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["保護 KVM 工作負載概述"]。



==== Oracle Database 工作負載增強功能

在此版本中、Oracle Database 工作負載引進下列增強功能：

* *Oracle AI Database 26ai 支援*：NetApp Backup and Recovery 現已支援 Oracle AI Database 26ai。
* *備份驗證支援*：您現在可以設定備份原則，以自動驗證 Oracle 資料庫備份的完整性。


有關保護 Oracle Database 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["保護 Oracle Database 工作負載概述"]。



==== VMware 工作負載增強功能

在此版本中、VMware 工作負載引進了以下增強功能：

* *跨資料存放區保護群組支援*：現在可以選擇在保護虛擬磁碟跨越多個資料存放區的虛擬機器時，保護群組的行為。
* *複製支援*：您現在可以從主要儲存設備和次要儲存設備建立虛擬機器快照的複製。


有關保護 VMware 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保護 VMware 工作負載概述"]。



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.05.1*：此版本包含 Trident Protect 26.05.1。
* *基於 VM 的應用程式就地還原*：現在您可以將基於 VM 的應用程式還原到原始命名空間和原始叢集。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



[[data-classification]]
=== 資料分類



==== 改善的組態頁面

Data Classification 已更新並改善了組態頁面，從而提升了使用者管理設定、系統、啟用掃描和監控系統運作狀況的體驗。新的組態頁面以更易於使用的格式保留了現有功能，並新增了按類型、錯誤狀態和掃描狀態篩選系統的功能。此外，新頁面還提供了已連接系統的摘要以及活動和已配置掃描的概覽。

檢閱 link:https://youtu.be/_8YJ3KyZ7nI["影片示範"^]。如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["使用資料分類掃描資料來源"^]。



==== Compliance 管理員 IAM 角色

資料分類功能現已支援合規性管理員角色，用於管理資料分類中的權限。合規性管理員角色無權存取包括 Console 代理和工作區在內的資源。擁有合規性管理員角色的使用者必須至少關聯一個其他角色。

安裝 Data Classification 時，您應該擁有 Console 平台管理員角色或 Compliance 管理員角色。

如果您是現有使用者，存取應照常進行。例如，擁有資料夾或專案管理員角色的平台角色擁有現有存取權。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Data Classification 角色"^]。



==== 使用 OVA 部署 Data Classification

NetApp Data Classification 現在支援使用 VMware Open Virtual Appliance（OVA）部署，為內部部署的 VMware vSphere 環境提供更簡化的部署策略。

有關更多資訊，請參閱link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["使用 OVA 部署 Data Classification"^]。



[[disaster-recovery]]
=== 災難復原



==== 基於 Kubernetes 的工作負載支援（預覽）

NetApp Disaster Recovery 現在已支援 Kubernetes 為基礎的工作負載。有了 Kubernetes 支援，您可以保護在 Kubernetes 叢集上執行的應用程式，包括 OpenShift Virtualization 環境。Disaster Recovery 支援 link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect 目前支援的任何 Kubernetes 版本"^]，確保容器化應用程式的無縫整合與強大的災難復原能力。

Kubernetes 型工作負載支援的主要功能：

* **廣泛的相容性**：Disaster Recovery 支援所有與 Trident Protect 相容的 Kubernetes 版本，包括 Red Hat OpenShift Virtualization。
* **以應用程式為中心的保護**：現在可以在應用程式層級保護 Kubernetes 工作負載，確保在容錯移轉事件期間恢復關鍵服務。
* **簡化編排**：災難復原提供直覺的工作流程，可自動備份和複製 Kubernetes 工作負載，運用與 VMware 環境相同的高效 SnapMirror 技術。


目前對基於 Kubernetes 的工作負載的支援處於預覽階段。若要開始保護基於 Kubernetes 的工作負載，請參閱 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["NetApp Disaster Recovery 的 Kubernetes 需求"^]。



[[ransomware-resilience]]
=== 勒索軟體抵禦能力



==== 乾淨還原增強功能

現在，乾淨還原功能支援還原到備用位置，讓您可以將磁碟區還原到由相同 Console 代理程式管理的不同系統、儲存 VM 和 Aggregate。此外，乾淨還原功能也取消了搜尋可用還原 Snapshot 的七天限制。現在，無論距離勒索軟體事件發生的時間遠近，乾淨還原功能都會持續搜尋可用 Snapshot 以找到可行的還原點。

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["使用乾淨還原來恢復工作負載"^]。



==== Google SecOps SIEM 支援

Ransomware Resilience 現已支援 Google SecOps 的安全資訊和事件管理 (SIEM)，使您能夠自動將資料傳送至 Google SecOps，從而簡化威脅分析和偵測。

如需組態資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["將 Ransomware Resilience 連接至 SIEM"^]。



==== Azure NetApp Files 支援現已正式推出

Ransomware Resilience 現已支援 Azure NetApp Files 系統，使您能夠有效率地偵測和應對 Azure NetApp Files 中的勒索軟體威脅。當您發現工作負載時，Ransomware Resilience 現在會顯示 Azure NetApp Files，並在保護儀表板中呈現。Ransomware Resilience 對 Azure NetApp Files 的支援包括僅使用快照的偵測和保護策略。對 Azure NetApp Files 的支援現已正式發布（GA）。

如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["了解勒索軟體復原能力"^]。



==== SOAR 支援封鎖使用者

Ransomware Resilience 現在支援使用 Google SecOps 和 Splunk SOAR playbook 封鎖單一使用者。透過此功能，當 Ransomware Resilience 偵測到可疑的使用者活動（例如資料外洩或大量刪除資料）時，您可以自動封鎖使用者。

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["整合 SOAR 劇本"^]。



[[05-may-2026]]
== 2026 年 5 月 05 日



[[backup-and-recovery]]
=== 備份和復原



==== Kubernetes 工作負載增強功能

在此版本中、Kubernetes 工作負載引入了以下增強功能：

* *Trident Protect 26.05*：此版本包含 Trident Protect 26.05。
* *從 Backup and Recovery 升級 Trident Protect*：如果您的 Kubernetes 叢集執行的是 Trident Protect 26.05 或更新版本，現在可以直接從 Backup and Recovery 升級 Trident Protect。
* *原生支援保護 VM*：現在您可以建立基於 VM 的應用程式，從而能夠以保護任何其他應用程式的方式保護虛擬機器。
* *資源轉換*：現在您可以使用資源轉換和資源轉換範本，在還原程序期間新增、移除和修改資源屬性。
* *檢視受保護的資源*：您現在可以檢視應用程式每個還原點中包含的資源，並下載詳細的 JSON 報告。這可讓您全面掌握還原點，並簡化稽核法規遵循作業。


有關保護 Kubernetes 工作負載的詳細資訊，請參閱 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保護 Kubernetes 工作負載概述"]。



[[27-april-2026]]
== 2026 年 4 月 27 日



[[keystone]]
=== Keystone

NetApp Console中Keystone儀表板的新增強功能：



==== 重新命名已佈建容量標籤

標籤 *Provisioned capacity* 已重新命名為 *Provisioned volume capacity*。更新後的標籤也已反映在相關的 CSV 和 Excel 報表中。



==== 累積高載的預測切換

您現在可以在 *Consumption trend* 標籤的 *Accrued burst* 檢視中使用 *Forecast* 切換按鈕，預測從目前日期起未來 120 天的累積突發流量使用量。若要深入瞭解，請參閱  https://docs.netapp.com/us-en/keystone-staas/integrations/consumption-tab.html#view-forecast-data["查看預測資料"]。
