---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: 了解NetApp Console的功能和資料服務的最新變化。 
---
= NetApp Console中的最新更改
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解NetApp Console的功能和資料服務的最新變化。要查看完整的發布歷史記錄，請訪問link:release-notes-index.html["全套發行說明"]針對每項單獨的服務。



== 管理功能

本節介紹與NetApp Console管理功能相關的新功能：組織、識別和存取、控制台代理、雲端提供者憑證等。



== 警報



== 適用於ONTAP 的Amazon FSx



== Amazon S3 存儲



== Azure Blob 儲存



== Azure NetApp Files



== 備份和復原



== 資料分類



== Cloud Volumes ONTAP



== 複製和同步



== 數位顧問



== Licenses and subscriptions



=== 2025年10月6日



==== BlueXP現在是NetApp Console

NetApp Console建立在增強和重組的BlueXP基礎之上，可在企業級內部和雲端環境中集中管理NetApp儲存和NetApp Data Services，提供即時洞察、更快的工作流程和簡化的管理，並且高度安全且合規。

有關更改的詳細信息，請參閱link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console發行說明"]。



=== 2025年3月10日



==== 可以刪除訂閱

如果您已取消訂閱，現在可以從數位錢包中刪除訂閱。



==== 查看 Marketplace 訂閱的已消耗容量

查看 PAYGO 訂閱時，您現在可以查看訂閱的已消耗容量。



=== 2025年2月10日

BlueXP digital wallet經過重新設計，易於使用，現在提供額外的訂閱和授權管理。



==== 新的概覽儀表板

數位錢包主頁具有更新的NetApp許可證和 Marketplace 訂閱儀表板，可深入了解特定服務、許可證類型和所需的操作。



==== 配置憑證訂閱

BlueXP digital wallet現在允許您配置對提供者憑證的訂閱。通常，您會在首次訂閱 Marketplace 訂閱或年度合約時執行此操作。以前，只能在「憑證」頁面上變更訂閱的憑證。



==== 將訂閱與組織關聯

現在您可以直接從數位錢包更新與訂閱關聯的組織。



==== 管理 Cloud Volume ONTAP許可證

現在您可以透過主頁或「直接許可證」標籤管理Cloud Volumes ONTAP許可證。使用“市場訂閱”選項卡查看您的訂閱資訊。



=== 2024年3月5日



==== BlueXP disaster recovery

BlueXP digital wallet現在讓您能夠管理BlueXP disaster recovery的許可證。您可以新增許可證、更新許可證以及查看有關許可證容量的詳細資訊。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["了解如何管理BlueXP資料服務的許可證"]



=== 2023年7月30日



==== 使用情況報告增強功能

Cloud Volumes ONTAP使用情況報告現已有幾項改進：

* TiB 單位現在包含在列名中。
* 現在包含一個用於序號的新_node(s)_欄位。
* 儲存虛擬機器使用情況報告下現在包含一個新的「工作負載類型」欄位。
* 工作環境名稱現在包含在儲存虛擬機器和磁碟區使用情況報告中。
* 卷類型_file_現在標記為_Primary (Read/Write)_。
* 磁碟區類型 _secondary_ 現在標記為 _Secondary (DP)_。


有關使用情況報告的更多信息，請參閱 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["下載使用情況報告"]。



== 災難復原



== E系列系統



== 生命週期規劃



== 邊緣緩存

邊緣快取服務於 2024 年 8 月 7 日刪除。



== Google Cloud NetApp Volumes



== Google 雲端儲存



== Keystone



== Kubernetes

2024 年 8 月 7 日，對發現和管理 Kubernetes 叢集的支援被取消。



== 遷移報告

遷移報告服務已於 2024 年 8 月 7 日移除。



== 本地ONTAP集群



== 營運彈性

營運彈性功能已於 2025 年 8 月 22 日移除。



== 勒索軟體抵禦能力



== 補救措施

補救服務已於 2024 年 4 月 22 日刪除。



== 複製



== 軟體更新



== StorageGRID



== 雲端分層



=== 2025年10月6日



==== BlueXP tiering現已更名NetApp Cloud Tiering

BlueXP tiering已重新命名為NetApp Cloud Tiering。



==== BlueXP現在是NetApp Console

NetApp Console建立在增強和重組的BlueXP基礎之上，可在企業級內部和雲端環境中集中管理NetApp儲存和NetApp Data Services，提供即時洞察、更快的工作流程和簡化的管理，並且高度安全且合規。

有關更改的詳細信息，請參閱link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console發行說明"]。



=== 2023年8月9日



==== 使用自訂前綴作為儲存桶名稱

過去，定義儲存桶名稱時需要使用預設的「fabric-pool」前綴，例如 _fabric-pool-bucket1_。現在您可以在命名儲存桶時使用自訂前綴。僅當將資料分層到 Amazon S3 時此功能才可用。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["了解更多"] 。



==== 在所有BlueXP連接器中搜尋集群

如果您使用多個連接器來管理環境中的所有儲存系統，則您想要實施分層的某些叢集可能位於不同的連接器中。如果您不確定哪個連接器正在管理某個集群，您可以使用 Cloud Tiering 在所有連接器中進行搜尋。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["了解更多"] 。



=== 2023年7月4日



==== 調整頻寬以傳輸非活動數據

當您啟動 Cloud Tiering 時， ONTAP可以使用無限量的網路頻寬將叢集中磁碟區中的非活動資料傳輸到物件儲存。如果您注意到分層流量影響了正常的使用者工作負載，您可以限制傳輸期間可使用的頻寬量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["了解更多"] 。



==== 通知中心顯示的分層事件

當叢集分層的冷資料少於 20%（包括未分層任何資料的叢集）時，分層事件「將叢集 <name> 中的其他資料分層到物件儲存以提高儲存效率」現在會作為通知出現。

此通知是一項“建議”，旨在幫助您提高系統效率並節省儲存成本。它提供了一個鏈接 https://www.netapp.com/data-services/tiering/tco-calculator/["Cloud Tiering 總擁有成本和節省計算器"^]幫助您計算成本節省。



== 卷緩存



== 工作負載工廠



=== 2025年10月6日



==== BlueXP workload factory現為NetApp Workload Factory

BlueXP已重新命名並重新設計，以更好地反映其在管理資料基礎架構中的作用。因此， BlueXP workload factory已重新命名為NetApp Workload Factory。



==== Ask Me 與 MCP 集成

Workload Factory 的 AI 助理 Ask Me 與模型上下文協定 (MCP) 整合。使用 MCP，Ask Me 可以安全地與外部環境互動並查詢 API 工具，以提供適合您特定儲存環境的回應。



=== 2025年10月5日



==== 儲存的新通知

NetApp Workload Factory通知服務包含針對儲存架構問題的通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory通知"]



=== 2025年9月9日



==== 儲存的新通知

BlueXP workload factory通知服務包括儲存自動容量管理通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP workload factory的通知"]
