= 已新增將磁碟區備份到 S3 配置的ONTAP系統上的儲存桶的支持
:allow-uri-read: 


[IMPORTANT]
====
* 由於重要的安全性增強，您的連接器現在需要對其他端點進行出站互聯網訪問，以便管理公有雲環境中的備份和復原資源。如果此端點尚未新增至防火牆的「允許」清單中，您將在 UI 中看到有關「服務不可用」或「無法確定服務狀態」的錯誤：
+
\ https://netapp-cloud-account.auth0.com

* 當您使用「CVO Professional」套件時，現在需要備份和還原 PAYGO 訂閱，該套件可讓您捆綁Cloud Volumes ONTAP和BlueXP backup and recovery。過去這並不是必需的。符合條件的Cloud Volumes ONTAP系統的備份和還原訂閱不會產生任何費用，但在任何新磁碟區上配置備份時需要付費。


====


=== 已新增將磁碟區備份到 S3 配置的ONTAP系統上的儲存桶的支持

現在，您可以使用已設定為簡單儲存服務 (S3) 的ONTAP系統將磁碟區備份到物件儲存。本機ONTAP系統和Cloud Volumes ONTAP系統皆支援此功能。此配置在雲端部署和沒有網際網路存取的本機位置（「私有」模式部署）中受支援。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["了解更多"] 。



=== 現在，您可以將受保護磁碟區中的現有快照包含在備份檔案中

過去，您可以將初始備份檔案中讀寫磁碟區的現有 Snapshot 副本包含到物件儲存中（而不是從最新的 Snapshot 副本開始）。只讀磁碟區（資料保護磁碟區）的現有 Snapshot 副本未包含在備份檔案中。現在您可以選擇將較舊的 Snapshot 副本包含在「DP」磁碟區的備份檔案中。

備份精靈會在備份步驟結束時顯示一個提示，您可以在其中選擇這些「現有快照」。



=== BlueXP backup and recovery不再支援將來新增的磁碟區的自動備份

以前，您可以在備份精靈中選取一個框，將選定的備份策略套用至新增至叢集的所有未來磁碟區。根據使用者回饋和此功能的使用不足，此功能已被刪除。您需要手動為新增至叢集的任何新磁碟區啟用備份。



=== 作業監控頁面已更新新功能

作業監控頁面現在提供更多與 3-2-1 備份策略相關的資訊。該服務還提供與備份策略相關的額外警報通知。

「備份生命週期」類型篩選器已重新命名為「保留」。使用此篩選器來追蹤備份生命週期並識別所有備份副本的到期時間。  「保留」作業類型會擷取在受BlueXP backup and recovery保護的磁碟區上啟動的所有快照刪除作業。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["了解有關更新的 Job Monitor 的更多信息"] 。
